

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(dplyr)
```


```{r}
#load data
growth_curve_data <- 
  read.delim("data/VIP205_Fig3_dilution-dye_cytometry_growth-curve.txt")

dye_dilution_cytometry <-
  read.delim("data/VIP205_Fig3_dilution-dye_cytometry.txt")

dye_dilution_microscopy <-
  read.delim("data/VIP205_Fig3_dilution-dye_microscopy.txt")


```


```{r}
growth_curve_data %>%
  dplyr::mutate(ID = paste(IPTG, rep)) %>%
  
  ####################################################################
  ggplot(aes(x = time, y = count_n, group = ID, linetype = IPTG)) +
  geom_line() +
  xlab("time (min)") +
  ylab("# bacteria/mL") +
  labs(linetype = "") +
  scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
  scale_x_continuous(breaks = seq(0, 180, by = 90)) +
  facet_grid(IPTG ~ .) +
  theme_classic2() +
  theme(
    legend.position = "top",        
    strip.text = element_blank(),    
    strip.background = element_blank(), 
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16))
```

```{r}

dye_dilution_cytometry %>%
dplyr::group_by(IPTG,time,cell_size_label,rep) %>%
  count() %>%
  group_by(IPTG, time, rep) %>%
  mutate(percent = 100 * n / sum(n)) %>%
  ungroup() %>%
  dplyr::filter(cell_size_label=="Filamentation") %>%
  
  dplyr::mutate(ID=paste(IPTG,rep)) %>%
  
  #############################################

  ggplot(aes(x=time,percent,group=ID,linetype=IPTG)) +
  geom_line() +
  ylab("Filamentation events (%)") +
  xlab("time (min)")+
  labs(linetype="") +
  scale_x_continuous(breaks = seq(0, 180, by = 90)) +
  facet_grid(IPTG~.) +
  theme_classic2() +
  theme(
    legend.position = "top",      
    strip.text = element_blank(),    
    strip.background = element_blank(), 
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16))
```

```{r}

dye_dilution_cytometry %>%
  dplyr::filter(time %in% c(0,90,180)) %>%
  dplyr::mutate(time = factor(paste0(time, " min"), levels = paste0(sort(unique(time)), " min"))) %>%
  
  
  #############################################################
  ggplot(aes(x=`SSC.Width`, y=log10(`FL4.A`/`SSC.Width`))) +
  geom_density_2d_filled(contour_var = "ndensity") +
  scale_fill_manual(values = c("transparent", colorRampPalette(c("gray", "black"))(9))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  ylab("eFlour670 (log10)") +
  xlab("SSC-Width (cell length)") +
  facet_grid(IPTG ~ time) +
  xlim(c(0,9000)) +
  theme_classic2() +
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 0.8),
    axis.text.y = element_text(size = 14),
    axis.text.x = element_text(size = 12),
    axis.title = element_text(size = 16),
    strip.text = element_text(size = 9) )
```


```{r}
 dye_dilution_microscopy %>%
  ggplot(aes(x=time,y=length_cell,group=cell_id)) +
  geom_line() +
  xlab("time (min)") +
  ylab("cell length (micrometers)") +
  theme_classic()
```
```{r}
dye_dilution_microscopy %>%
  ggplot(aes(x=time,y=DsRed,group=cell_id)) +
  geom_line() +
  xlab("time (min)") +
  ylab("cell length (micrometers)") +
  theme_classic()
```

